#! /bin/bash
#
# chkconfig: 345 <STARTORDER>
# description: Weblogic Servers Startup

# source function library
. /etc/rc.d/init.d/functions

NM_PORT=<NMPORT>
DOMAIN_NAME=<DOMAINNAME>
APP_SERVER_NAME=<APPSERVERNAME>
ROOT_WEBLOGIC=<ROOTWEBLOGIC>

USER_PROPERTIES=/wls/admin/config/nmuser.properties
USER_KEY=/wls/admin/config/nmuser.key
DOMAIN_DIR="/wls/admin/domains/${DOMAIN_NAME}"
SERVER_HOST=`hostname -s`.exa-internal.intra.corp
PROTO=ssl

start()
{
	echo -n "Starting Server $APP_SERVER_NAME on $DOMAIN_NAME Domain:"
	su - wls -c "/export/scripts/weblogic/StartupServices/manage_server.sh $SERVER_HOST $NM_PORT $USER_PROPERTIES $USER_KEY $DOMAIN_NAME $DOMAIN_DIR $PROTO start $APP_SERVER_NAME $ROOT_WEBLOGIC" >/dev/null 2>&1
	[ $? -eq 0 ] && success || failure
	echo
	touch /var/lock/subsys/$DOMAIN_NAME.$APPSERVERNAME
}

stop()
{
	echo -n "Stopping Server $APP_SERVER_NAME on $DOMAIN_NAME Domain:"
	su - wls -c "/export/scripts/weblogic/StartupServices/manage_server.sh $SERVER_HOST $NM_PORT $USER_PROPERTIES $USER_KEY $DOMAIN_NAME $DOMAIN_DIR $PROTO stop $APP_SERVER_NAME $ROOT_WEBLOGIC" >/dev/null 2>&1
	[ $? -eq 0 ] && success || failure
	echo
	rm -f /var/lock/subsys/$DOMAIN_NAME.$APPSERVERNAME
}

status()
{
	echo -n "The server $APP_SERVER_NAME on the $DOMAIN_NAME Domain is:"
        su - wls -c "/export/scripts/weblogic/StartupServices/manage_server.sh $SERVER_HOST $NM_PORT $USER_PROPERTIES $USER_KEY $DOMAIN_NAME $DOMAIN_DIR $PROTO status $APP_SERVER_NAME $ROOT_WEBLOGIC" >/dev/null 2>&1
	case "$?" in 
		1) echo "Error on NodeManager"
		;;
		2) echo "Request Failed"
		;;
		10) echo "SHUTDOWN"
		;;
		11) echo "STARTING"
		;;
		12) echo "STANDBY"
		;;
		13) echo "ADMIN"
		;;
		14) echo "RESUMING"
		;;
		15) echo "RUNNING"
		;;
		16) echo "SUSPENDING"
		;;
		17) echo "FORCE_SUSPENDING"
		;;
		18) echo "SHUTTING_DOWN"
		;;
		19) echo "FAILED"
		;;
		*) echo "UNKNOW"
		;;
	esac
}

case "$1" in
	start)
        start
        ;;
    stop)
	stop
	;;
    restart)
	stop
	start
        ;;
    status)
	status
	;;
    *)
echo $"Usage: $0 {start|stop|restart|status}"
esac
